AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

Style/AlignParameters:
  Enabled: false
Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
